### PR TITLE
fix:webpack 5 support

### PR DESCRIPTION
**Pull request by hardiksukhadiya**
fix:works in webpack 5 and also tested all the test cases and all are working fine

### CODE REVIEW

**Comment by lucsorel** [comment]
hello @hardiksukhadiya 

Thank you for the PR. I am not sure that the changes are enough to work with webpack5. The two examples (with reveal.js and remark.js) break when upgrading to wepack5

**Comment by hardiksukhadiya** [comment]
@lucsorel Thank you for your remarks. Let me have a look into that and will get to back you.

**Comment by hardiksukhadiya** [comment]
> hello @hardiksukhadiya
> 
> Thank you for the PR. I am not sure that the changes are enough to work with webpack5. The two examples (with reveal.js and remark.js) break when upgrading to wepack5

There was an issue of html-webpack-plugin which is not compatible with webpack 5 version. So I've updated version of it in both the example and tested and it seems like working fine. 

Can you please check the updated changes and let me know if you still face any issue?

**Comment by lucsorel** [comment]
thanks for looking at it. I will test the PR this week :+1:

**Comment by hardiksukhadiya** [comment]
@lucsorel Did you get a chance to look a PR?

**Comment by lucsorel** [comment]
the fix did not seem to work for Reveal.js, the markdown code for the image is properly adapted with the asset path but then the reveal plugin does not replace it by the html code to include the image:
image

This is beyond the purpose of the PR. So I downgraded some versions of the dependencies so that the reveal.js example work with webpack 4.x and an old version of reveal.js.

I have updated the version of the library in the root `package.json`, added you as a contributor and fixed the version of some dependencies in the examples for them to work.

Is that ok with you?

**Comment by lucsorel** [comment]
out of curiosity, what is your use-case of this markdown-image-loader?

**Comment by hardiksukhadiya** [comment]
> version 3.0.0, contributors, adapted examples

We are using it for one of our product which has the use case to give a support of local images in markdown file and because webpack version has been updated to 5, we have to do changes in this package as well either by downloading this package in a local and do changes accordingly or by submitting our changes in your repo and to take an approval from you. So if others are using the same package they also will have a benefits of using it in a webpack 5 version.

**Comment by hardiksukhadiya** [comment]
> the fix did not seem to work for Reveal.js, the markdown code for the image is properly adapted with the asset path but then the reveal plugin does not replace it by the html code to include the image: image
> 
> This is beyond the purpose of the PR. So I downgraded some versions of the dependencies so that the reveal.js example work with webpack 4.x and an old version of reveal.js.
> 
> I have updated the version of the library in the root `package.json`, added you as a contributor and fixed the version of some dependencies in the examples for them to work.
> 
> Is that ok with you?

Yes, that is fine. Regarding Reveal.js, I've tested that we had the same issue in webpack 4 as well but our images were properly adapted in asset directory and for the same in webpack 5 as well. So I hadn't check in details as you told this is beyond the purpose of the PR.

So Now , Can you merge this PR ? As this changes looks fine for me and it will work on webpack 5 as well.

**Review by lucsorel — APPROVED** [review]

**Comment by lucsorel** [comment]
merged and published at https://www.npmjs.com/package/markdown-image-loader

:pray: thank you very much for your contribution :smiley:

**Comment by hardiksukhadiya** [comment]
> merged and published at https://www.npmjs.com/package/markdown-image-loader
> 
> 🙏 thank you very much for your contribution 😃

Thank you for your support as well 🙏

**Pull request merged**
